# Configuración de JWT
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://miempresa.com/issuer

# Configuración de firma (para JwtService.generateToken)
smallrye.jwt.sign.key.location=privateKey.pem

# Base de datos
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=12345
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/Facturador
quarkus.hibernate-orm.database.generation=update

# Permitir acceso público al login
quarkus.http.auth.permission.public.paths=/auth/login,/auth/register
quarkus.http.auth.permission.public.policy=permit
# Todo lo demás requiere autenticación
quarkus.http.auth.permission.protected.paths=/*
quarkus.http.auth.permission.protected.policy=authenticated